name: Build Wayshot

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy rustfmt

    - name: Install wayland dependencies
      run: |
        pacman -Syu --noconfirm egl-wayland egl-gbm wayland base-devel mesa pango cairo

    - name: Build
      run: |
        rm Cargo.lock
        cargo build --release

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: wayshot-binary
        path: target/release/wayshot  # <- ini binary hasil build

    - name: Clippy check
      run: cargo clippy -- -D warnings

    - name: Check test
      run: cargo test --verbose
